import {
  textToLexical,
  readLocalFile,
  richTextFromNodes,
  paragraph,
  boldParagraph,
} from './helpers'

export interface ProductSeedData {
  name: string
  slug: string
  shortDescription: string
  introProduct?: string
  description?: string
  characteristics?: string[]
  ingredients?: string
  allergens?: string
  nutritionalValues?: string
  weight: string
  price: number
  category: 'regular' | 'sweet' | 'occasional'
  available: boolean
  availabilityText?: string
  featured: boolean
  imageFile: string
}

export const products: ProductSeedData[] = [
  // ===== REGULAR PRODUCTS (9 with full detail) =====
  {
    name: 'Paine mixta',
    slug: 'paine-mixta',
    shortDescription: 'Paine artizanala cu maia naturala, fermentata lent si coapta pe vatra. Gust echilibrat, miez elastic si coaja subtire.',
    introProduct: 'Paine artizanala cu maia naturala, fermentata lent si coapta pe vatra. Are gust echilibrat, miez elastic si coaja subtire, potrivita pentru consum zilnic.',
    description: 'Painea mixta cu maia este facuta din faina alba tip 650, faina integrala si faina de secara, cu adaos de seminte de in. Este o paine echilibrata, potrivita pentru masa de zi cu zi. Fermentatia lenta, intre 24 si 48 de ore, ajuta la dezvoltarea gustului si a texturii. Produsul nu contine drojdie comerciala, aditivi sau amelioratori.',
    characteristics: [
      'Fermentatie lenta, intre 24 si 48 de ore',
      'Maia naturala',
      'Fara drojdie comerciala',
      'Fara aditivi si amelioratori',
      'Coapta pe vatra',
      'Potrivita pentru consum zilnic',
      'Livrare marti si vineri',
    ],
    ingredients: 'Apa, faina alba tip 650, faina integrala, faina de secara, maia naturala, sare, seminte de in.',
    allergens: 'Contine gluten. Poate contine urme de seminte, nuci, lapte, oua sau alte alergene, deoarece produsele sunt preparate in aceeasi brutarie.',
    nutritionalValues: 'Energie 235 kcal | Proteine 8 g | Carbohidrati 43 g | Zaharuri 1.2 g | Grasimi 3.2 g | Fibre 4.5 g | Sare 1.2 g (per 100g)',
    weight: '800g',
    price: 23,
    category: 'regular',
    available: true,
    featured: true,
    imageFile: 'PXL_20260319_121417485.PORTRAIT-scaled.jpg',
  },
  {
    name: 'Paine integrala',
    slug: 'paine-integrala',
    shortDescription: 'Paine cu maia naturala din faina integrala si seminte de in. Gust intens, textura consistenta si aroma cerealelor integrale.',
    introProduct: 'Paine cu maia naturala, fermentata lent, realizata din faina integrala si seminte de in. Are gust intens, textura consistenta si aroma specifica cerealelor integrale.',
    description: 'Painea integrala cu maia este realizata din faina integrala de grau, apa, sare, maia naturala integrala si seminte de in. Este o paine cu gust pronuntat, textura consistenta si miez elastic. Fermentatia lenta contribuie la dezvoltarea gustului si a structurii produsului. Nu contine drojdie comerciala, aditivi sau amelioratori.',
    characteristics: [
      'Fermentatie lenta',
      'Maia naturala integrala',
      'Fara drojdie comerciala',
      'Fara aditivi si amelioratori',
      'Contine seminte de in',
      'Coapta pe vatra',
      'Livrare marti si vineri',
    ],
    ingredients: 'Apa, faina integrala de grau, maia naturala integrala, sare, seminte de in.',
    allergens: 'Contine gluten. Poate contine urme de seminte, nuci, lapte, oua sau alte alergene, deoarece produsele sunt preparate in aceeasi brutarie.',
    nutritionalValues: 'Energie 228 kcal | Proteine 8.7 g | Carbohidrati 40 g | Zaharuri 1.1 g | Grasimi 3.4 g | Fibre 7.1 g | Sare 1.2 g (per 100g)',
    weight: '800g',
    price: 26,
    category: 'regular',
    available: true,
    featured: true,
    imageFile: 'PXL_20250403_072532656.PORTRAIT-scaled.jpg',
  },
  {
    name: 'Paine fara gluten',
    slug: 'paine-fara-gluten',
    shortDescription: 'Paine fara gluten cu faina de mei, orez, hrisca, seminte de chia si tarate de psyllium. Gust aromat si textura echilibrata.',
    introProduct: 'Paine fara gluten, realizata din fainuri si ingrediente selectate, cu fermentatie lenta si coacere pe vatra. Are gust aromat, textura echilibrata si miez umed si elastic.',
    description: 'Painea fara gluten este realizata fara faina de grau si fara alte cereale care contin gluten. Reteta foloseste ingrediente precum faina de mei, faina de orez, faina de hrisca, seminte de chia si tarate de psyllium. Fermentatia lenta contribuie la dezvoltarea gustului si la obtinerea unei texturi mai echilibrate. Coacerea pe vatra ofera o coaja placuta si o aroma specifica.',
    characteristics: [
      'Fara gluten',
      'Fermentatie lenta',
      'Fara drojdie comerciala',
      'Fara aditivi si amelioratori',
      'Contine seminte de chia',
      'Contine tarate de psyllium',
      'Coapta pe vatra',
      'Livrare marti si vineri',
    ],
    ingredients: 'Apa, faina de mei, faina de orez, faina de hrisca, seminte de chia, tarate de psyllium, maia fara gluten, sare.',
    allergens: 'Produs realizat fara gluten. Poate contine urme de nuci, seminte, lapte, oua sau alte alergene, deoarece produsele sunt preparate in aceeasi brutarie.',
    nutritionalValues: 'Energie 228 kcal | Proteine 5.4 g | Carbohidrati 42 g | Zaharuri 1.3 g | Grasimi 4.1 g | Fibre 6.2 g | Sare 1.2 g (per 100g)',
    weight: '500g',
    price: 32,
    category: 'regular',
    available: true,
    availabilityText: 'Disponibila doar vinerea',
    featured: false,
    imageFile: 'PXL_20231107_194546274.jpg',
  },
  {
    name: 'Paine San Joaquin',
    slug: 'paine-san-joaquin',
    shortDescription: 'Paine cu maia naturala inspirata de stilul San Joaquin Sourdough. Miez aerat, aroma intensa si coaja subtire.',
    introProduct: 'Paine cu maia naturala, fermentata lent, inspirata de stilul San Joaquin Sourdough. Are miez aerat, aroma intensa si coaja subtire, potrivita pentru cei care prefera o paine alba, simpla si expresiva.',
    description: 'Painea San Joaquin cu maia este facuta din faina alba tip 650, apa, sare si maia naturala. Este o paine cu structura aerata, miez elastic si gust bine dezvoltat prin fermentatie lenta. Nu contine drojdie comerciala, aditivi sau amelioratori. Este coapta pe vatra si gandita ca o paine de zi cu zi, dar cu o textura mai deschisa si mai aerata decat painea mixta.',
    characteristics: [
      'Fermentatie lenta',
      'Maia naturala',
      'Fara drojdie comerciala',
      'Fara aditivi si amelioratori',
      'Miez aerat si elastic',
      'Coaja subtire si crocanta',
      'Coapta pe vatra',
      'Livrare marti si vineri',
    ],
    ingredients: 'Apa, faina alba tip 650, maia naturala, sare.',
    allergens: 'Contine gluten. Poate contine urme de seminte, nuci, lapte, oua sau alte alergene, deoarece produsele sunt preparate in aceeasi brutarie.',
    nutritionalValues: 'Energie 240 kcal | Proteine 8.5 g | Carbohidrati 45 g | Zaharuri 1 g | Grasimi 1.4 g | Fibre 2.8 g | Sare 1.2 g (per 100g)',
    weight: '800g',
    price: 24,
    category: 'regular',
    available: true,
    featured: true,
    imageFile: 'PXL_20231113_161014336.PORTRAIT-scaled.jpg',
  },
  {
    name: 'Paine de secara',
    slug: 'paine-de-secara',
    shortDescription: 'Paine cu maia naturala realizata exclusiv din faina de secara. Gust intens, aroma specifica si miez dens si hidratat.',
    introProduct: 'Paine cu maia naturala, fermentata lent si realizata exclusiv din faina de secara. Are gust intens, aroma specifica si un miez dens si hidratat.',
    description: 'Painea de secara cu maia este facuta exclusiv din faina de secara, apa, sare si maia naturala din secara. Este o paine cu personalitate puternica, gust usor acidulat si textura specifica. Fermentatia lenta contribuie la dezvoltarea aromei si a structurii produsului. Nu contine drojdie comerciala, aditivi sau amelioratori.',
    characteristics: [
      'Fermentatie lenta',
      'Maia naturala din secara',
      'Fara drojdie comerciala',
      'Fara aditivi si amelioratori',
      'Realizata exclusiv din secara',
      'Miez dens si hidratat',
      'Coapta pe vatra',
      'Livrare marti si vineri',
    ],
    ingredients: 'Apa, faina de secara, maia naturala din secara, sare.',
    allergens: 'Contine gluten. Poate contine urme de seminte, nuci, lapte, oua sau alte alergene, deoarece produsele sunt preparate in aceeasi brutarie.',
    nutritionalValues: 'Energie 215 kcal | Proteine 7.2 g | Carbohidrati 39 g | Zaharuri 1 g | Grasimi 1.6 g | Fibre 7.8 g | Sare 1.2 g (per 100g)',
    weight: '800g',
    price: 28,
    category: 'regular',
    available: true,
    featured: true,
    imageFile: 'PXL_20260319_121337121.jpg',
  },
  {
    name: 'Chifle',
    slug: 'chifle',
    shortDescription: 'Set de 5 chifle cu maia naturala, coapte pe vatra. Coaja subtire, miez elastic si aroma inspirata din painile brutariei.',
    introProduct: 'Set de 5 chifle cu maia naturala, fermentate lent si coapte pe vatra. Au coaja subtire, miez elastic si aroma inspirata din diferite tipuri de paine din brutarie.',
    description: 'Chiflele sunt realizate din aluaturi diferite, inspirate din painile produse in brutarie. Setul contine combinatii de chifle pe baza de aluat San Joaquin, paine mixta si paine integrala. Unele variante contin ierburi mediteraneene, iar fiecare chifla pastreaza specificul tipului de paine din care provine. Fermentatia lenta contribuie la dezvoltarea gustului si a texturii.',
    characteristics: [
      'Set de 5 chifle',
      'Fermentatie lenta',
      'Maia naturala',
      'Fara drojdie comerciala',
      'Fara aditivi si amelioratori',
      'Textura elastica si coaja subtire',
      'Inspirate din aluaturile brutariei',
      'Coapte pe vatra',
      'Livrare marti si vineri',
    ],
    ingredients: 'Apa, faina alba tip 650, faina integrala, faina de secara, maia naturala, sare, ierburi mediteraneene.',
    allergens: 'Contine gluten. Poate contine urme de seminte, nuci, lapte, oua sau alte alergene, deoarece produsele sunt preparate in aceeasi brutarie.',
    nutritionalValues: 'Energie 238 kcal | Proteine 8 g | Carbohidrati 44 g | Zaharuri 1.1 g | Grasimi 2.2 g | Fibre 4.2 g | Sare 1.2 g (per 100g)',
    weight: 'Set 5 buc',
    price: 20,
    category: 'regular',
    available: true,
    featured: false,
    imageFile: 'PXL_20260504_151443071.jpg',
  },
  {
    name: 'Bagheta mixta cu piper',
    slug: 'bagheta-mixta-cu-piper',
    shortDescription: 'Bagheta cu maia naturala din aluat de paine mixta, finisata cu crusta de piper. Miez elastic si aroma echilibrata.',
    introProduct: 'Bagheta cu maia naturala, realizata din aluat de paine mixta si finisata cu o crusta acoperita cu piper. Are miez elastic, aroma echilibrata si coaja subtire si aromata.',
    description: 'Bagheta mixta cu piper este realizata din acelasi aluat folosit pentru painea mixta, pe baza de faina alba tip 650, faina integrala si faina de secara, cu adaos de seminte de in. Crusta este acoperita cu piper, care adauga o aroma condimentata si un gust mai intens. Fermentatia lenta contribuie la dezvoltarea texturii si a gustului.',
    characteristics: [
      'Fermentatie lenta',
      'Maia naturala',
      'Fara drojdie comerciala',
      'Fara aditivi si amelioratori',
      'Contine seminte de in',
      'Crusta acoperita cu piper',
      'Coapta pe vatra',
      'Livrare marti si vineri',
    ],
    ingredients: 'Apa, faina alba tip 650, faina integrala, faina de secara, maia naturala, sare, seminte de in, piper.',
    allergens: 'Contine gluten. Poate contine urme de seminte, nuci, lapte, oua sau alte alergene, deoarece produsele sunt preparate in aceeasi brutarie.',
    nutritionalValues: 'Energie 236 kcal | Proteine 8 g | Carbohidrati 43 g | Zaharuri 1.2 g | Grasimi 3.3 g | Fibre 4.5 g | Sare 1.2 g (per 100g)',
    weight: '800g',
    price: 32,
    category: 'regular',
    available: true,
    featured: false,
    imageFile: 'PXL_20241014_153325148.PORTRAIT-1.jpg',
  },
  {
    name: 'Bagheta integrala cu piper',
    slug: 'bagheta-integrala-cu-piper',
    shortDescription: 'Bagheta cu maia naturala din aluat integral, finisata cu crusta de piper. Gust intens si aroma cerealelor integrale.',
    introProduct: 'Bagheta cu maia naturala, realizata din aluat integral si finisata cu o crusta acoperita cu piper. Are aproximativ 800 g, gust intens, textura consistenta si aroma specifica cerealelor integrale.',
    description: 'Bagheta integrala cu piper este realizata din acelasi aluat folosit pentru painea integrala, pe baza de faina integrala de grau, maia naturala integrala si seminte de in. Crusta este acoperita cu piper, care adauga o aroma condimentata si un gust mai intens. Fermentatia lenta contribuie la dezvoltarea gustului si a texturii.',
    characteristics: [
      'Fermentatie lenta',
      'Maia naturala integrala',
      'Fara drojdie comerciala',
      'Fara aditivi si amelioratori',
      'Contine seminte de in',
      'Crusta acoperita cu piper',
      'Coapta pe vatra',
      'Livrare marti si vineri',
    ],
    ingredients: 'Apa, faina integrala de grau, maia naturala integrala, sare, seminte de in, piper.',
    allergens: 'Contine gluten. Poate contine urme de seminte, nuci, lapte, oua sau alte alergene, deoarece produsele sunt preparate in aceeasi brutarie.',
    nutritionalValues: 'Energie 229 kcal | Proteine 8.7 g | Carbohidrati 40 g | Zaharuri 1.1 g | Grasimi 3.5 g | Fibre 7.1 g | Sare 1.2 g (per 100g)',
    weight: '800g',
    price: 35,
    category: 'regular',
    available: true,
    featured: false,
    imageFile: 'PXL_20241014_153333505.jpg',
  },
  {
    name: 'Bagheta cu unt',
    slug: 'bagheta-cu-unt',
    shortDescription: 'Bagheta cu maia naturala si unt, tehnica Yudane. Miez moale, aroma fina si coaja delicata.',
    introProduct: 'Bagheta cu maia naturala si unt, realizata prin tehnica Yudane pentru un miez moale si elastic. Are aproximativ 400 g, aroma fina si o coaja subtire si delicata.',
    description: 'Bagheta cu unt este realizata din faina alba si maia naturala, folosind tehnica Yudane pentru obtinerea unei texturi mai moi si mai elastice. Reteta contine unt in proportie de aproximativ 10% raportat la cantitatea de faina, ceea ce contribuie la gustul bogat si la textura delicata a produsului. Fermentatia lenta ajuta la dezvoltarea aromei si a structurii baghetei, iar coacerea pe vatra ofera o coaja subtire si placuta.',
    characteristics: [
      'Fermentatie lenta',
      'Maia naturala',
      'Tehnica Yudane',
      'Contine unt',
      'Miez moale si elastic',
      'Fara aditivi si amelioratori',
      'Coapta pe vatra',
      'Livrare marti si vineri',
    ],
    ingredients: 'Apa, faina alba tip 650, maia naturala, unt, sare.',
    allergens: 'Contine gluten si lapte. Poate contine urme de seminte, nuci, oua sau alte alergene, deoarece produsele sunt preparate in aceeasi brutarie.',
    nutritionalValues: 'Energie 275 kcal | Proteine 7.5 g | Carbohidrati 42 g | Zaharuri 1.3 g | Grasimi 8.5 g | Fibre 2.6 g | Sare 1.2 g (per 100g)',
    weight: '400g',
    price: 23,
    category: 'regular',
    available: true,
    featured: false,
    imageFile: 'Gilu-118-1.jpg',
  },

  // ===== SWEET PRODUCTS (1) =====
  {
    name: 'Biscotti cu portocala si ghimbir',
    slug: 'biscotti-cu-portocala-si-ghimbir',
    shortDescription: 'Aroma intensa de portocala si ghimbir. Biscotti artizanali cu textura crocanta.',
    weight: '200g',
    price: 41,
    category: 'sweet',
    available: true,
    featured: false,
    imageFile: 'PXL_20241031_191358190.jpg',
  },

  // ===== OCCASIONAL PRODUCTS (18) =====
  {
    name: 'Biscotti clasici',
    slug: 'biscotti-clasici',
    shortDescription: 'Biscotti cu migdale si textura crocanta. Preparat artizanal.',
    weight: '200g',
    price: 34,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20240406_061225132-1.jpg',
  },
  {
    name: 'Cos cadou artizanal',
    slug: 'cos-cadou-artizanal',
    shortDescription: 'Selectie de produse artizanale. Ideal pentru cadouri sau evenimente.',
    weight: '-',
    price: 350,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20231223_122930747.jpg',
  },
  {
    name: 'Cozonac cu nuca',
    slug: 'cozonac-cu-nuca',
    shortDescription: 'Umplutura bogata de nuca si miez pufos. Cozonac artizanal cu maia.',
    weight: '1000g',
    price: 150,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20231124_114503546.jpg',
  },
  {
    name: 'Cozonac cu mac',
    slug: 'cozonac-cu-mac',
    shortDescription: 'Umplutura bogata de mac si miez pufos. Cozonac artizanal cu maia.',
    weight: '1000g',
    price: 150,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20231213_193853377.jpg',
  },
  {
    name: 'Hencleș',
    slug: 'hencles',
    shortDescription: 'Desert traditional cu aluat dospit. Preparat artizanal.',
    weight: 'Pachet',
    price: 120,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20251212_094323699.jpg',
  },
  {
    name: 'Mini cozonac Top Floare',
    slug: 'mini-cozonac-top-floare',
    shortDescription: 'Decor ornamental si umplutura bogata. Preparat artizanal in editie limitata.',
    weight: '-',
    price: 180,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20260404_091130984.jpg',
  },
  {
    name: 'Paine cu chili si sos de rosii',
    slug: 'paine-cu-chili-si-sos-de-rosii',
    shortDescription: 'Gust intens si aroma usor picanta. Paine artizanala cu maia.',
    weight: '800g',
    price: 32,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20240328_194726772.jpg',
  },
  {
    name: 'Paine cu nuca',
    slug: 'paine-cu-nuca',
    shortDescription: 'Miez aromat cu nuca crocanta. Paine artizanala cu maia.',
    weight: '800g',
    price: 35,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20240220_202328428.jpg',
  },
  {
    name: 'Paine cu ceapa si cartof copt',
    slug: 'paine-cu-ceapa-si-cartof-copt',
    shortDescription: 'Aroma intensa de ceapa coapta. Paine artizanala cu maia.',
    weight: '800g',
    price: 32,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20231123_200235625.jpg',
  },
  {
    name: 'Paine cu usturoi copt',
    slug: 'paine-cu-usturoi-copt',
    shortDescription: 'Gust bogat si aroma intensa de usturoi copt. Paine artizanala cu maia.',
    weight: '800g',
    price: 32,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20231123_190310170.jpg',
  },
  {
    name: 'Paine cu dovleac copt si seminte',
    slug: 'paine-cu-dovleac-copt-si-seminte',
    shortDescription: 'Miez moale si aroma de dovleac. Paine artizanala cu maia.',
    weight: '800g',
    price: 32,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'IMG-20211022-WA0016.jpg',
  },
  {
    name: 'Paine Oshawa',
    slug: 'paine-oshawa',
    shortDescription: 'Paine integrala cu gust rustic. Preparat artizanal cu maia.',
    weight: '600g',
    price: 32,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: '20210419_191126.jpg',
  },
  {
    name: 'Focaccia cu rosii cherry si masline',
    slug: 'focaccia-cu-rosii-cherry-si-masline',
    shortDescription: 'Rosii cherry, masline si rozmarin. Focaccia artizanala cu maia.',
    weight: '300g',
    price: 37,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: '20211118_160936.jpg',
  },
  {
    name: 'Focaccia Barese',
    slug: 'focaccia-barese',
    shortDescription: 'Preparata din grau dur si rosii cherry. Focaccia artizanala cu maia.',
    weight: '300g',
    price: 39,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20260319_121228725.jpg',
  },
  {
    name: 'Focaccia cu ceapa si otet balsamic',
    slug: 'focaccia-cu-ceapa-si-otet-balsamic',
    shortDescription: 'Gust intens si aroma dulce-acrisoara. Focaccia artizanala cu maia.',
    weight: '300g',
    price: 39,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20260319_121156319.jpg',
  },
  {
    name: 'Paine cu malai',
    slug: 'paine-cu-malai',
    shortDescription: 'Gust rustic si textura bogata. Paine artizanala cu maia.',
    weight: '800g',
    price: 32,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20260115_201717622.jpg',
  },
  {
    name: 'Saleuri',
    slug: 'saleuri',
    shortDescription: 'Fragede si intens aromate. Preparat artizanal.',
    weight: '200g',
    price: 35,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'original_99a76956-34dd-425e-a384-dbf0fcbeeed6_PXL_20240405_175212098.jpg',
  },
  {
    name: 'Paine ornamentala',
    slug: 'paine-ornamentala',
    shortDescription: 'Baza San Joaquin cu decor din aluat integral. Paine ornamentala cu aspect floral.',
    weight: '850g',
    price: 40,
    category: 'occasional',
    available: true,
    featured: false,
    imageFile: 'PXL_20231120_131658897-1.jpg',
  },
]
